export const SCENARIOS = [
  {
    id: 'mystery',
    number: '?',
    title: '未知的夜晚',
    subtitle: 'THE HOUSE CHOOSES',
    type: '探索 · 组合触发',
    difficulty: '未知',
    time: '20–35 分钟',
    color: '#a6b9c4',
    intro:
      '你们只知道自己走进了这栋房子。预兆与发现它的房间，将共同揭示今晚的故事。',
    objective: '探索宅邸，发现预兆。',
    limit: 12,
  },
  {
    id: 'werewolf',
    number: '04',
    title: '月光照进来的时候',
    subtitle: 'WHEN MOONLIGHT ENTERS',
    type: '狼人 · 感染围猎',
    difficulty: '标准',
    time: '20–30 分钟',
    color: '#a8bce0',
    intro: '窗外的月亮越来越近。有人捂住手腕，藏起一道已经愈合的伤。',
    haunt:
      '一名队友化为狼王。月光房间使狼群力量 +1。封窗、治疗狼毒，或完成两处月印后回入口解咒。感染者有三个完整行动轮自救，随后加入狼群。',
    objective: '击败全部狼人；或净化两处月印，再到入口完成解咒。',
    limit: 12,
    ending: '银色光芒洗去狼毒。窗外的月亮终于退回夜空，幸存者重新认出了彼此。',
  },
  {
    id: 'bells',
    number: '01',
    title: '第十三声钟响',
    subtitle: 'THE THIRTEENTH BELL',
    type: '背叛 · 封印仪式',
    difficulty: '入门',
    time: '15–20 分钟',
    color: '#be9d64',
    intro:
      '一封没有署名的邀请函，将你们带到这座废弃宅邸。午夜将至，钟楼却已经响了十二次。',
    haunt:
      '钟声穿过墙壁。沈墨放下手中的书，露出一个陌生的微笑。「最后一声，需要你们留下。」他成为守钟人。封住三处祭坛，阻止第十三声钟响。',
    objective: '在倒计时结束前，封印三座祭坛。',
    limit: 10,
    ending:
      '最后一枚封印落下，钟摆停在午夜之前。门外的晨光照进来，而你们身后，再也没有脚步声。',
  },
  {
    id: 'mirror',
    number: '02',
    title: '镜中来客',
    subtitle: 'A STRANGER IN THE GLASS',
    type: '调查 · 寻找真身',
    difficulty: '标准',
    time: '15–20 分钟',
    color: '#8fa9ae',
    intro:
      '失踪的朋友寄来一张合照。照片里所有人都背对镜头，只有镜中的倒影在看着你。',
    haunt:
      '所有镜子同时亮起。倒影晚了一拍才模仿你的动作。检查三面古镜，找到并击败藏在其中的镜魇；空镜中的银屑可以强化你们的攻击。',
    objective: '调查古镜，找到镜魇真身并击败它。',
    limit: 12,
    ending:
      '裂纹从镜子的中央蔓延，那个微笑终于消失。你们走出宅邸时，终于听见自己的脚步与影子重合。',
  },
  {
    id: 'flood',
    number: '03',
    title: '深水之下',
    subtitle: 'WHAT LIES BELOW',
    type: '协作 · 限时逃生',
    difficulty: '紧张',
    time: '15–20 分钟',
    color: '#77a09a',
    intro: '暴雨封住山路。你们推开宅邸的门避雨，却闻到一股来自深海的咸腥味。',
    haunt:
      '黑水从地板缝隙涌出。门锁失去电力，水下有东西在靠近。找到两枚保险丝，修复发电机，然后让所有幸存者回到入口逃生。',
    objective: '收集2枚保险丝 → 修复发电机 → 全员回到入口逃生。',
    limit: 10,
    ending:
      '电流重新点亮门锁。你们推开大门，最后一人跃上台阶。黑水吞没了大厅，水中的手只抓住一片衣角。',
  },
];
export const FLOORS = [
  { id: 1, name: '二楼', label: 'UPPER FLOOR' },
  { id: 0, name: '一楼', label: 'GROUND FLOOR' },
  { id: -1, name: '地下室', label: 'BASEMENT' },
];
export const TRAITS = {
  might: '力量',
  speed: '速度',
  sanity: '理智',
  knowledge: '知识',
};
export const TRAIT_KEYS = Object.keys(TRAITS);
export const HEROES = [
  {
    name: '林岚',
    role: '调查记者',
    mark: '岚',
    color: '#d1b16e',
    start: { might: 3, speed: 4, sanity: 4, knowledge: 4 },
    tracks: {
      might: [0, 2, 2, 3, 3, 4, 5, 6, 8],
      speed: [0, 2, 3, 3, 4, 4, 5, 6, 7],
      sanity: [0, 2, 3, 3, 4, 5, 5, 6, 8],
      knowledge: [0, 2, 3, 4, 4, 5, 6, 7, 8],
    },
  },
  {
    name: '顾野',
    role: '野外向导',
    mark: '野',
    color: '#7da79c',
    start: { might: 4, speed: 4, sanity: 3, knowledge: 3 },
    tracks: {
      might: [0, 3, 3, 4, 4, 5, 6, 7, 8],
      speed: [0, 2, 3, 4, 4, 5, 6, 7, 8],
      sanity: [0, 2, 2, 3, 3, 4, 5, 6, 7],
      knowledge: [0, 1, 2, 3, 3, 4, 5, 6, 7],
    },
  },
  {
    name: '沈墨',
    role: '民俗学者',
    mark: '墨',
    color: '#b393bd',
    start: { might: 3, speed: 3, sanity: 4, knowledge: 4 },
    tracks: {
      might: [0, 1, 2, 2, 3, 3, 4, 5, 6],
      speed: [0, 2, 2, 3, 3, 4, 5, 6, 7],
      sanity: [0, 3, 3, 4, 4, 5, 6, 7, 8],
      knowledge: [0, 3, 3, 4, 5, 5, 6, 7, 8],
    },
  },
  {
    name: '许宁',
    role: '急诊医生',
    mark: '宁',
    color: '#c88f7b',
    start: { might: 3, speed: 3, sanity: 4, knowledge: 4 },
    tracks: {
      might: [0, 2, 2, 3, 3, 4, 5, 6, 7],
      speed: [0, 2, 3, 3, 4, 4, 5, 6, 7],
      sanity: [0, 2, 3, 4, 4, 5, 6, 7, 8],
      knowledge: [0, 2, 3, 3, 4, 5, 6, 7, 8],
    },
  },
  {
    name: '陆星',
    role: '摄影师',
    mark: '星',
    color: '#8badd0',
    start: { might: 3, speed: 4, sanity: 3, knowledge: 4 },
    tracks: {
      might: [0, 1, 2, 3, 3, 4, 5, 6, 7],
      speed: [0, 3, 3, 4, 5, 5, 6, 7, 8],
      sanity: [0, 2, 2, 3, 3, 4, 5, 6, 8],
      knowledge: [0, 2, 2, 3, 4, 5, 5, 6, 7],
    },
  },
  {
    name: '唐禾',
    role: '古物修复师',
    mark: '禾',
    color: '#b7bc82',
    start: { might: 3, speed: 3, sanity: 4, knowledge: 4 },
    tracks: {
      might: [0, 2, 2, 3, 4, 4, 5, 6, 7],
      speed: [0, 2, 2, 3, 3, 4, 4, 5, 6],
      sanity: [0, 2, 3, 4, 5, 5, 6, 7, 8],
      knowledge: [0, 2, 3, 4, 4, 5, 6, 7, 8],
    },
  },
];
// Each room is a physical tile in a shuffled deck. Doors rotate clockwise: N/E/S/W.
const room = (id, name, art, floors, doors, icon, special = null) => ({
  id,
  name,
  art,
  floors,
  doors,
  icon,
  special,
  windows: [
    'bedroom',
    'nursery',
    'observatory',
    'greenhouse',
    'winter',
    'gallery',
    'ballroom',
  ].includes(id)
    ? [0, 1, 2, 3].filter((d) => !doors.includes(d)).slice(0, 2)
    : [],
  tags: [
    'bedroom',
    'nursery',
    'observatory',
    'greenhouse',
    'winter',
    'ballroom',
  ].includes(id)
    ? ['moon']
    : ['mirror', 'gallery', 'crypt'].includes(id)
      ? ['memory']
      : ['well', 'laundry', 'boiler'].includes(id)
        ? ['water']
        : ['ritual'],
});
export const ROOM_DECK = [
  room('mystic-elevator', '神秘电梯', 7, [-1, 0, 1], [2], null, 'elevator'),
  room('collapsed-room', '坍塌房间', 4, [0, 1], [0, 1, 2], null, 'collapse'),
  room('library', '藏书室', 1, [0, 1], [0, 1, 2], 'event', 'knowledge'),
  room('dining', '宴会厅', 2, [0], [0, 1, 3], 'item'),
  room('chapel', '祈祷室', 3, [0, 1], [0, 2], 'omen', 'sanity'),
  room('bedroom', '旧卧室', 4, [1], [0, 1], 'event'),
  room('greenhouse', '温室', 5, [0], [0, 1, 2], 'item', 'might'),
  room('ritual', '地下祭室', 6, [-1], [0, 2], 'omen'),
  room('boiler', '锅炉房', 7, [-1], [0, 1, 2], 'item'),
  room('mirror', '镜廊', 8, [0, 1], [0, 2], 'omen'),
  room('stairs-down', '地下阶梯', 6, [0], [0, 1, 2], null, 'stairsDown'),
  room('nursery', '育婴室', 4, [1], [0, 3], 'omen'),
  room('study', '书房', 1, [0, 1], [0, 1], 'event'),
  room('kitchen', '废弃厨房', 2, [0], [0, 1, 2], 'item'),
  room('crypt', '家族墓室', 6, [-1], [0, 1], 'omen'),
  room('attic', '阁楼储藏间', 4, [1], [0, 2], 'item'),
  room('workshop', '木工房', 7, [-1, 0], [0, 2, 3], 'item'),
  room('gallery', '肖像长廊', 8, [0, 1], [0, 2], 'event'),
  room('ballroom', '舞厅', 2, [0, 1], [0, 1, 2, 3], 'omen'),
  room('wine', '酒窖', 6, [-1], [0, 1, 2], 'event'),
  room('observatory', '观星室', 5, [1], [0, 1], 'omen'),
  room('laundry', '洗衣房', 7, [-1, 0], [0, 2], 'item'),
  room('music', '音乐室', 3, [0, 1], [0, 1, 3], 'event'),
  room('shrine', '无名神龛', 3, [-1, 0], [0, 2], 'omen'),
  room('servants', '佣人房', 4, [-1, 1], [0, 1, 2], 'event'),
  room('archive', '档案室', 1, [-1, 1], [0, 1], 'item'),
  room('winter', '冬日花房', 5, [0, 1], [0, 2, 3], 'event'),
  room('well', '枯井间', 6, [-1], [0, 1, 3], 'omen'),
  room('clock', '钟表室', 8, [0, 1], [0, 1, 2], 'omen'),
  room('storage', '杂物间', 7, [-1, 0, 1], [0, 2], 'item'),
  room('hallway', '幽暗走廊', 8, [-1, 0, 1], [0, 1, 2, 3], null),
  room('crossing', '交叉回廊', 0, [-1, 0, 1], [0, 1, 2, 3], null),
  room('secret-study', '密藏书库', 1, [-1, 1], [0, 2, 3], 'omen'),
  room('guest', '客房', 4, [0, 1], [0, 1, 2], 'event'),
  room('vault', '保险库', 7, [-1], [0, 1], 'item'),
  room('altar', '烛光礼拜堂', 3, [-1, 1], [0, 1, 2], 'omen'),
  room('laboratory', '炼金实验室', 7, [-1, 1], [0, 2], 'event'),
  room('garden', '室内庭院', 5, [0], [0, 1, 2, 3], 'event'),
];
export const EVENTS = [
  {
    id: 'whisper',
    title: '墙后的低语',
    story: '墙里的声音知道你的名字。它正在请求你开门。',
    trait: 'sanity',
    threshold: 4,
    success: { trait: 'sanity', delta: 1, text: '你辨清了幻觉，理智提升1格。' },
    failure: {
      damage: 'mental',
      amount: 2,
      text: '低语挥之不去，承受2点精神伤害。',
    },
  },
  {
    id: 'boards',
    title: '腐朽的地板',
    story: '脚下传来一声脆响。你的重量压断了朽木。',
    trait: 'speed',
    threshold: 4,
    success: {
      trait: 'speed',
      delta: 1,
      text: '你及时跃过裂隙，速度提升1格。',
    },
    failure: {
      damage: 'physical',
      amount: 2,
      text: '你摔进碎木之中，承受2点肉体伤害。',
    },
  },
  {
    id: 'cipher',
    title: '墙上的密码',
    story: '褪色的墙纸后，藏着一串不停变化的字符。',
    trait: 'knowledge',
    threshold: 4,
    success: {
      trait: 'knowledge',
      delta: 1,
      text: '你解开了密码，知识提升1格。',
    },
    failure: {
      trait: 'sanity',
      delta: -1,
      text: '字符钻进脑海，理智下降1格。',
    },
  },
  {
    id: 'door',
    title: '沉重的铁门',
    story: '铁门正慢慢闭合，门后传来熟悉的求救声。',
    trait: 'might',
    threshold: 4,
    success: { trait: 'might', delta: 1, text: '你撑开铁门，力量提升1格。' },
    failure: {
      damage: 'physical',
      amount: 1,
      text: '铁门夹伤了你，承受1点肉体伤害。',
    },
  },
  {
    id: 'portrait',
    title: '多出来的肖像',
    story: '画框中的脸，分明是年老后的你。',
    trait: 'sanity',
    threshold: 3,
    success: {
      trait: 'knowledge',
      delta: 1,
      text: '你从画框发现了日期，知识提升1格。',
    },
    failure: {
      trait: 'sanity',
      delta: -1,
      text: '未来的目光令你颤抖，理智下降1格。',
    },
  },
  {
    id: 'footsteps',
    title: '楼上的脚步',
    story: '你走一步，楼上就响两声。有人正在追上你。',
    trait: 'speed',
    threshold: 4,
    success: {
      trait: 'speed',
      delta: 1,
      text: '你摆脱了脚步声，速度提升1格。',
    },
    failure: {
      damage: 'mental',
      amount: 1,
      text: '脚步声停在你的头顶，承受1点精神伤害。',
    },
  },
  {
    id: 'ash',
    title: '炉灰中的名字',
    story: '灰烬里写着几个人名，最后一个还是空白。',
    trait: 'knowledge',
    threshold: 3,
    success: {
      trait: 'sanity',
      delta: 1,
      text: '你抹去了诅咒的标记，理智提升1格。',
    },
    failure: {
      damage: 'mental',
      amount: 1,
      text: '手指被冰冷的灰烬缠住，承受1点精神伤害。',
    },
  },
  {
    id: 'cold',
    title: '刺骨的寒意',
    story: '一阵寒风从紧闭的窗户吹来，影子冻在墙上。',
    trait: 'might',
    threshold: 3,
    success: { trait: 'might', delta: 1, text: '你扛住了寒意，力量提升1格。' },
    failure: {
      trait: 'speed',
      delta: -1,
      text: '你的关节变得僵硬，速度下降1格。',
    },
  },
  {
    id: 'lantern',
    title: '未熄的灯',
    story: '一盏油灯在等待来客，温暖似乎仍然真实。',
    effect: {
      trait: 'sanity',
      delta: 1,
      text: '你重新镇定下来，理智提升1格。',
    },
  },
  {
    id: 'notes',
    title: '前人的手记',
    story: '纸页的最后一句写着：不要相信镜中的人。',
    effect: {
      trait: 'knowledge',
      delta: 1,
      text: '手记提供了线索，知识提升1格。',
    },
  },
];
export const ITEMS = [
  {
    id: 'medkit',
    title: '急救箱',
    story: '药箱里还有干净的绷带。',
    effect: '使用一次：力量或速度恢复2格，最多恢复到起始位置。',
    use: 'healPhysical',
    consumable: true,
  },
  {
    id: 'tonic',
    title: '安神药',
    story: '磨砂瓶上还有医生的字迹。',
    effect: '使用一次：理智或知识恢复2格，最多恢复到起始位置。',
    use: 'healMental',
    consumable: true,
  },
  {
    id: 'crowbar',
    title: '撬棍',
    story: '一件足够趁手的工具。',
    effect: '力量攻击额外投1枚骰子（同类效果不叠加）。',
    bonus: 'attack',
  },
  {
    id: 'flashlight',
    title: '手电筒',
    story: '光束终于穿透了房间的黑暗。',
    effect: '事件的知识或理智检定额外投1枚骰子。',
    bonus: 'event',
  },
  {
    id: 'boots',
    title: '登山靴',
    story: '鞋底的纹路还很清晰。',
    effect: '每回合初始移动力 +1。',
    bonus: 'movement',
  },
  {
    id: 'tools',
    title: '精密工具',
    story: '工具盒里每一件物品都摆放整齐。',
    effect: '剧本目标的知识检定额外投1枚骰子。',
    bonus: 'ritual',
  },
  {
    id: 'coffee',
    title: '浓缩咖啡',
    story: '你从未如此需要这点苦味。',
    effect:
      '使用后弃置，本回合剩余移动力 +2。若已因抽取预兆或休整停止移动，咖啡不能让你恢复移动；请留到下一回合饮用。',
    use: 'movement',
    consumable: true,
  },
  {
    id: 'lucky',
    title: '幸运硬币',
    story: '不论抛多少次，它都落在掌心。',
    effect: '任意属性检定额外投1枚骰子。',
    bonus: 'all',
  },
  {
    id: 'bandage',
    title: '止血绷带',
    story: '一卷尚未拆开的绷带。',
    effect: '使用一次：力量或速度恢复2格，最多恢复到起始位置。',
    use: 'healPhysical',
    consumable: true,
  },
  {
    id: 'tea',
    title: '宁神茶',
    story: '茶香让你想起离这栋房子很远的地方。',
    effect: '使用一次：理智或知识恢复2格，最多恢复到起始位置。',
    use: 'healMental',
    consumable: true,
  },
];
export const OMENS = [
  {
    id: 'bell',
    title: '无舌铜铃',
    story: '铃里空无一物，你却听见它在响。',
    trait: 'sanity',
    delta: 1,
    effect: '获得时理智提升1格。',
  },
  {
    id: 'book',
    title: '空白之书',
    story: '当你的手碰到纸页，墨迹开始浮现。',
    trait: 'knowledge',
    delta: 1,
    effect: '获得时知识提升1格。',
  },
  {
    id: 'mask',
    title: '裂面的面具',
    story: '面具内侧留下了温热的呼吸。',
    trait: 'might',
    delta: 1,
    effect: '获得时力量提升1格。',
  },
  {
    id: 'compass',
    title: '逆行罗盘',
    story: '指针总是指向你刚刚离开的房间。',
    trait: 'speed',
    delta: 1,
    effect: '获得时速度提升1格。',
  },
  {
    id: 'locket',
    title: '银色吊坠',
    story: '吊坠中的照片被人小心地剪去了脸。',
    trait: 'sanity',
    delta: 1,
    effect: '获得时理智提升1格；持有时精神伤害减少1。',
    hauntEffects: {
      werewolf:
        '治疗自己或同室人物的狼毒时，治疗检定 +2。治疗者或被治疗者持有吊坠均有效，双方都持有时仍只加2。',
    },
    rules: [
      {
        when: { phase: 'haunt', scenario: 'werewolf' },
        patch: { cureBonus: 2 },
      },
    ],
    bonus: 'mentalWard',
  },
  {
    id: 'bone',
    title: '刻字的骨片',
    story: '骨片上的划痕像一张微型地图。',
    trait: 'knowledge',
    delta: 1,
    effect: '获得时知识提升1格。',
  },
  {
    id: 'doll',
    title: '沉睡的布偶',
    story: '它的眼睛在你眨眼的时候闭上。',
    trait: 'sanity',
    delta: -1,
    effect: '获得时理智下降1格；持有者每次精神伤害减少1点。',
    bonus: 'mentalWard',
  },
  {
    id: 'key',
    title: '温热的钥匙',
    story: '你确信它原本握在另一个人的手里。',
    trait: 'speed',
    delta: 1,
    effect: '获得时速度提升1格。',
  },
  {
    id: 'mirror-shard',
    title: '银镜碎片',
    story: '碎片中映出的房间里没有你。',
    trait: 'knowledge',
    delta: 1,
    effect: '获得时知识提升1格。',
  },
  {
    id: 'thorn',
    title: '荆棘冠',
    story: '干枯的枝条里渗出了新鲜的血。',
    trait: 'might',
    delta: 1,
    effect: '获得时力量提升1格。',
  },
  {
    id: 'candle',
    title: '不灭烛',
    story: '烛火没有温度，也不会被风吹灭。',
    trait: 'sanity',
    delta: 1,
    effect: '获得时理智提升1格。',
  },
  {
    id: 'eye',
    title: '石中之眼',
    story: '石头的纹理正在缓慢转向你。',
    trait: 'knowledge',
    delta: 1,
    effect: '获得时知识提升1格。',
  },
];
